select * from "Customer ID" limit 20

select *from "Customer ID"

update "Customer ID"
set purchase_freq_days = 90
where "Frequency of Purchases" = 'Quarterly';

----To see the column Names
SELECT column_name
FROM information_schema.columns
WHERE table_name = 'Customer ID';

----Q1. What is the total Rev generated by male vs female customer?

select "Gender", sum("Purchase Amount (USD)") as Revenue
from "Customer ID"
group by "Gender"

----Q2. Which Customers used discount but still spent more than the avg purchase amount

Select "Customer ID", "Purchase Amount (USD)"
from "Customer ID"
where "Discount Applied" = 'Yes' and "Purchase Amount (USD)" >= (Select Avg("Purchase Amount (USD)") from "Customer ID")

-----Q3. Which are the top 5 prodcts with highest Average review rating?

Select "Item Purchased", Round(Avg("Review Rating"::numeric),2) as "Average_Review"
from "Customer ID"
group by "Item Purchased"
order by avg("Review Rating") desc 
limit 5;

----Q4. Compare the avg purchase amounts betw Standard and express shipping

Select "Shipping Type", Round(Avg("Purchase Amount (USD)"),2) as "Average Purchase Amount"
from "Customer ID"
where "Shipping Type" in ('Standard','Express')
group by "Shipping Type"

----Q5. Do Subscribed customers spends more? Compare Avg spend and total Revenue
---Between subscribers and non - subscribers

Select Count("Customer ID") as "Total Customers", "Subscription Status", Round(Avg("Purchase Amount (USD)"),2) as "Purchase_Amnt", sum("Purchase Amount (USD)") as "Total Revenue"
from "Customer ID"
Group by "Subscription Status"
order by "Total Revenue" , "Purchase_Amnt" desc

----Q6. which 5 product have the Highest percentage of purchases with discounts applied?

Select "Item Purchased", Round(100 * sum(Case when "Discount Applied" = 'Yes' then 1 else 0 End)/count(*),2) as "discount rate"
from "Customer ID"
Group by "Item Purchased"
order by "discount rate" desc
limit 5

---Q7. Segment Customers into new , returning and loyal based on their total 
----number of previous purchases, and show the count of each segment

with "Customer_type" as (
Select "Customer ID", "Previous Purchases",
CASE 
when "Previous Purchases" = 1 then 'New'
when "Previous Purchases" Between 2 and 10 then 'Returning'
else 'Loyal'
End as "Customer Segment"
from "Customer ID" 
)
Select "Customer Segment", Count(*) as "Number of Customers"
from "Customer_type"
group by "Customer Segment"

---Q8. what are the top 3 purchased products within the category

with "item_counts" as (
select "Category", "Item Purchased",
count("Customer ID") as "Total_orders",
row_number() over(partition by "Category" order by count("Customer ID") desc) as item_rank
from "Customer ID"
group by "Category", "Item Purchased"
)
Select "item_rank", "Category", "Item Purchased", "Total_orders"
from "item_counts"
where "item_rank" <=3

---Q9. Are customers who are repeat buyers 
---(more than 5 previous purchases) also likely to subscribe?

Select "Subscription Status", count("Customer ID") as "repeat_buyers"
from "Customer ID"
where "Previous Purchases" > 5
group by "Subscription Status"

---Q10. What is the revenue contribution of each age group?

select "age_group",sum("Purchase Amount (USD)") as "Revenue"
from "Customer ID"
group by "age_group"
order by "Revenue" desc





